services:
  ######################################################## Zookeeper ########################################################
  # http://sleuthkit.org/autopsy/docs/user-docs/4.18.0/install_solr_page.html
  zookeeper:
    image: zookeeper:${ZOOKEEPER_VERSION}
    container_name: 'autopsy-zookeeper'
    restart: unless-stopped
    hostname: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - default
      - autopsy-backend
    ports:
      - "${SERVER_IP}:${ZOOKEEPER_HOST_PORT}:2181"
    volumes:
      - zk-data:/data
      - zk-logs:/datalog
  
  ######################################################## Solr ########################################################
  # http://sleuthkit.org/autopsy/docs/user-docs/4.18.0/install_solr_page.html
  solr:
    container_name: 'autopsy-solr'
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile-solr
      args:
        - SOLR_VERSION=${SOLR_VERSION}
    environment:
      ZK_HOST: zookeeper:2181
      SOLR_VERSION: ${SOLR_VERSION}
      SOLR_JAVA_MEM: ${SOLR_JAVA_MEM}
    networks:
      - default
      - autopsy-backend
    ports:
      - "${SERVER_IP}:${SOLR_HOST_PORT}:8983"
    volumes:
      - solr-data:/var/solr
    depends_on: 
      - zookeeper
    cpus: 4
    mem_limit: ${SOLR_CONTAINER_MEMORY}

  ######################################################## ActiveMQ ########################################################
  # http://sleuthkit.org/autopsy/docs/user-docs/4.18.0/install_activemq_page.html
  activemq:
    container_name: 'autopsy-activemq'
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile-activemq
      args:
        - ACTIVEMQ_VERSION=${ACTIVEMQ_VERSION}
        - AUTOPSY_USERNAME=${AUTOPSY_USERNAME}
        - AUTOPSY_PASSWORD=${AUTOPSY_PASSWORD}
    networks:
      - default
      - autopsy-backend
    environment:
      ACTIVEMQ_OPTS_MEMORY: ${ACTIVEMQ_OPTS_MEMORY}
    ports:
      - "${SERVER_IP}:${ACTIVEMQ_HOST_PORT}:61616"
    volumes: 
      - activemq-config:/opt/activemq/conf
      - activemq-data:/opt/activemq/data
    mem_limit: ${ACTIVEMQ_CONTAINER_MEMORY}

  ######################################################## Postgres ########################################################
  # http://sleuthkit.org/autopsy/docs/user-docs/4.18.0/install_postgresql_page.html
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: 'autopsy-postgres'
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "fsync=off"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "full_page_writes=off"
      - "-c"
      - "max_connections=100"
    environment:
      - POSTGRES_DB=autopsy
      - POSTGRES_USER=${AUTOPSY_USERNAME}
      - POSTGRES_PASSWORD=${AUTOPSY_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
    networks:
      - default
      - autopsy-backend
    ports:
      - "${SERVER_IP}:${POSTGRES_HOST_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  ######################################################## SAMBA storage server ########################################################
  samba:
    image: dockurr/samba
    container_name: 'autopsy-samba'
    profiles:
      - samba
    restart: unless-stopped
    environment:
      USER: "${AUTOPSY_USERNAME}"
      PASS: "${AUTOPSY_PASSWORD}"
    ports:
      - "${SERVER_IP}:${SAMBA_HOST_PORT_NMBD_137}:137/udp" # required to advertise shares (NMBD)
      - "${SERVER_IP}:${SAMBA_HOST_PORT_NMBD_138}:138/udp" # required to advertise shares (NMBD)
      - "${SERVER_IP}:${SAMBA_HOST_PORT_SMB_139}:139/tcp" # default smb port
      - "${SERVER_IP}:${SAMBA_HOST_PORT_SMB_445}:445/tcp" # default smb port
    networks:
      - default
      - autopsy-backend
    volumes:
      - .\conf\docker\samba\smb.conf:/etc/samba/smb.conf:ro
      - samba-storage:/storage

volumes:
  solr-data:
  zk-data:
  zk-logs:
  pg-data:
  activemq-config:
  activemq-data:
  samba-storage:

networks: 
  autopsy-backend:
